### ISSUE TITLE
Unified scoring levels

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/wikimo_content#50]
Current standard: https://wiki.mozilla.org/Security/Standard_Levels#Scoring_levels

The standard levels are not used consistently which recently started to cause confusion among teams and reduces our communication efficiency. It is important to have expectations regarding our levels and scores - which ideally never (or very rarely) need to change.

Issues
======
- Star rating only used in https://mana.mozilla.org/wiki/display/POLICIES/Standard%3A+Individual+Password+Managers (also used in past infosec reports, no longer used)

- A-F rating (non-standard) rating used in https://mozilla.github.io/http-observatory-website/analyze.html?host=mozilla.com

- Modern-intermediate-old compatibility levels non-standardized and misunderstood as scoring levels in https://mozilla.github.io/http-observatory-website/analyze.html?host=mozilla.com, https://wiki.mozilla.org/Security/Server_Side_TLS, https://wiki.mozilla.org/Security/Guidelines/OpenSSH, https://wiki.mozilla.org/Security/Guidelines/Web_Security, https://wiki.mozilla.org/Security/Guidelines/Key_Management (potentially more pages)

- sec-other, sec-low, sec-moderate, sec-high, sec-critical flags rating levels used in bugzilla https://wiki.mozilla.org/WebAppSec/Filing_In_Bugzilla#Adding_Keywords and other keywords from https://wiki.mozilla.org/Security_Severity_Ratings

Proposals
========

1) Make usage of standard levels actually non-optional. While the page says so, it is not enforced (i.e. self-police within the team)

2) Back-link all pages using the standard levels to https://wiki.mozilla.org/Security/Standard_Levels (just like some pages also link to RFC2119 for the same reasons)

3) **Unify scoring levels**

3.1) Remove the star rating. I believe it's a decent rating as per rationale - it also favors having 5 stars everywhere (no half measures), but it sadly did not see much adoption.

3.2) Adopt A-F rating and officially document it. It is used by ssllabs and is well understood. Arguably, people are either A, B, or "bad up to F" (which is similar to star rating, which would be 1 star, 3 stars or 5 stars). A- A+ etc not allowed as it makes the rating unclear.

3.3) Discuss modern-intermediate-old (also should it be Modern-legacy-deprecated?). In particular not using "modern" automatically means you're not getting a 5 star or "A" rating - thus it actually make sense, that people understood it as a scoring rating - it affects your score directly.

3.4) Document bugzilla keywords directly in  https://wiki.mozilla.org/Security/Standard_Levels and discuss the current nomenclature (can we alias sec-critical to sec-maximum and use the normal levels?)

3.5) Revamp https://wiki.mozilla.org/Security_Severity_Ratings and clearly deprecate all keywords that are no longer used (wsec, opsec for ex). Add rationale on how keywords are added and why it's a good idea to keep the list small.

Multi-ping: @jeffbryner  @amuntner @Phrozyn  @claudijd @tristanweir

_Please refer to the above by using the numbered point for conciseness (or add points after 3.5 if anything is missing. Something like "I agree with 1, 2, 3 but would do 3.2 differently: here's why" would be good). This issue is meant as a general discussion - if necessary each point might become its own issue. For now, I saw value in keeping context together._

**Comment by jeffbryner** [comment]
I'd be in favor of adopting the A-F rating in 3.2 since it's familiar, widely understood and easily referenced by execs. The use case would be rating adherence to a configuration standard like the observatory or even the TLS config guidelines. 

I also believe we should unify the wsec- ratings in bugzilla to match these standard levels (i.e. wsec-critical becomes wsec-maximum) mentioned in 3.4 and 3.5

**Comment by jeffbryner** [comment]
Maybe time for another multi-ping ;-]

**Comment by gdestuynder** [comment]
Sent direct emails just now

**Comment by marumari** [comment]
I'm fine with us acting on just an A-F scale, that is, treating A+ the same as A-, but I do really like having the option for them to be there.  If you just have A, B, C, D, and F, your scale can only have five steps.  Sometimes that's perfectly great, but sometimes you want to have more range.

**Comment by jeffbryner** [comment]
" A- A+ etc not allowed as it makes the rating unclear." I don't see how it makes it unclear? Can you expand on this @gdestuynder ?

**Comment by tristanweir** [comment]
3.3 - I prefer modern-legacy-deprecated, as intermediate denotes a transition state and there may be cases where the owner has no intent to transition. Furthermore, deprecated more clearly means "quit using this", where as "old" doesn't have a value ascribed to it.

I agree on all the other points.

Additional comment: Risk levels, Effort levels, and Security levels all use the same nomenclature (Low, Med, High, Max) but correlate to very different things. For example, a problem might provide very little exposure (Low risk), be hard to fix (High Effort), and be part of a service that uses security best practices only (Medium security). It's important that we be very explicit about which metric we're talking about when we stamp a Low/Medium/High/Maximum box on something.

**Comment by marumari** [comment]
I don't know if I like "legacy" -- this is the recommended configuration for your average website.  I think modern-typical-deprecated or something along those lines seems good though.

**Comment by claudijd** [comment]
1.) Works for me
2.) Works for me
3.1) I support the removal of ***** rating (I've never used it myself or seen it used)
3.2.) I'm fine with grading scale (I'm also not in favor of a +/- scale)
3.3) I'm find with s/old/deprecated/, I'm also fine with not being able to get an A unless your modern
3.4) Agree we should document, also agree we should use the same levels
3.5) Agreed

In the end, my main interest with this effort is to unify on a rating scale rather than having 5-6 scales.  I personally don't care all that much what we use, just as long as we're consistent going forward.

**Comment by floatingatoll** [comment]
In some video games, "S" is used as the "Superb" rating above A. It's
generally considered unachievable by most people, but provides a way to
reward those who do literally every possible thing to perfection with their
own special badge. Perhaps that's of some use here, if y'all truly desire
to indicate "better than A" somehow.

**Comment by marumari** [comment]
I love S, but I suspect that most non-Japanese people won't get it.  Perhaps I could make it a top secret grade at some point, for the very highest score of 130/100?  Could even make it gold and sparkly and everything.  :)

**Comment by floatingatoll** [comment]
As an outside, I can get behind A+, then A..F, without any A- or B+ or any
of that. A+ is a well known thing, if you're not A+, IMO you don't really
want gradiations beyond a single letter tier.

**Comment by jeffbryner** [comment]
Yeah, I can understand an A+ (go github.com!)

**Comment by mpurzynski** [comment]
1 - ACK. Peer reviews should help enforce it. Your page cannot be "Ready" if it does not use standard wording.
2 - ACK
3.1 - Remove it. I've never used that and A-F levels speak better to C-level.
3.2 - Adopt the A-F ratings, since it kind of became industry standard and is widely understood.
3.3 - modern - intermediate - depreceated. As long as we define the mapping we will be OK.
3.4 - Unify bugzilla keywords with other documents
3.5 - That page needs to be rewritten

**Comment by gdestuynder** [comment]
@mpurzynski @tristanweir @marumari 
>  3.3 - modern - intermediate - depreceated. As long as we define the mapping we will be OK.
My main issue with this one is that we currently recommend intermediate, but that will give you a bad score. Punished for following our guidance seems like that issue to me, and adds to the confusion between which levels mean what.
I wonder if we should just have "recommended" and "deprecated" - but of course any change here might affect people (thought arguably most just copy paste the config then wonder why they don't get an A rating)

@jeffbryner  @marumari @floatingatoll @claudijd 
> 3.2 " A- A+ etc not allowed as it makes the rating unclear." I don't see how it makes it unclear? Can you expand on this @gdestuynder ?
That's 18 scores. I believe the goal of scoring is not to make everyone "happy they're not F" but instead everyone safe (which makes even A-B-C-D-E-F or A-B-C-D-F to be a lot of ratings).
Generally we have:
"you're safe, use a good configuration and future proofed as much as you could" (A+, A, A- ratings)
"you're safe for now but that's not the greatest config and could be at more risk specially toward  (B+ to E- ratings?) powerful threat actors"
"you're not safe with this config" (F+, F, F- ratings?)

It means only 3 ratings are *really* relevant from a pragmatic security point of view.
The rest is feel-good stuff to either make-believe you're safer than you are, or instigate some motivation for site owners to improve as they can see gradual improvements (but they're still not using the safe config!) <= which is still a valid thing to do

Just like 1-5 stars is a balance of that, I think A-F is a balance. A+ to F- seems too far off the balance to me. A+ to F seems like an option as well as it's still somewhat balanced (this one seems to be the consensus)

@tristanweir 
It is true that we use LOW-MEDIUM-HIGH-MAXIMUM a good bit and it's important to always indicate for what they're used, I can try to make that clearer when editing the doc.
One thing I like about these 4 levels though is that in all cases they indicate something very similar - i.e. without fully knowing what the document author may be talking about or label the levels as, if I know one document using these I know what is meant without looking it up.

**Comment by gdestuynder** [comment]
**Summary of current conversation:**
Everything from the first comment are currently good to implement, except 3.3 and 3.2 where we need to finish flushing it out:

3.3) We have to decide on A+,A,B,C,D,E,F. This one seem to have the most concensus and could be what we end up using if everyone's ok with that. I would also always want to have a label next to the score such as:

A+, A (Safe) #Technically one could argue you're never 100% safe, albeit it seems like it communicate well what the security community think is currently safe.
B, C (Acceptable)
D,E,F (Unsafe)


3.2) we have to decide what to do with modern-intermediate-old. I don't see a clear cut on this. In a vacuum I'd replace them with a different, clear wording even thus it may cause some confusion to switch. 

My current proposal would be to just have "recommended" "recommended for legacy clients" "deprecated" (and I'm aware changing current wording would cause some confusion).
Rationale: it's clear what's recommended and not recommended. It's clear it's not a rating.
Once we get some clarity on 3.2 I'll also get some feedback from ulfr since he started the "rating" for it.

Also, another ping for @amuntner since everyone agrees on changing bugzilla levels and you haven't chimed in

**Comment by marumari** [comment]
> My main issue with this one is that we currently recommend intermediate, but that will give you a bad score. Punished for following our guidance seems like that issue to me, and adds to the confusion between which levels mean what.

Where does it get a bad score?  It's "Intermediate" (with a green "I") on the Observatory, and it gets an A+ on SSL Labs.

> Just like 1-5 stars is a balance of that, I think A-F is a balance. A+ to F- seems too far off the balance to me. A+ to F seems like an option as well as it's still somewhat balanced (this one seems to be the consensus)

Yep, I'm okay with A+ to F.  I think that reflects the actual grading system.  Note that I cut out "E" in the HTTP Observatory, and that there has never been an F+ or F-.  :)

**Comment by Phrozyn** [comment]
Finally going to chime in on this:

>1) Make usage of standard levels actually non-optional. While the page
says so, it is not enforced (i.e. self-police within the team)

A: I'm good with this, but I don't know how you'll enforce it across
mozilla - unless this is only within the team? You'd need a team to
moderate.

>2) Back-link all pages using the standard levels to
https://wiki.mozilla.org/Security/Standard_Levels (just like some pages
also link to RFC2119 for the same reasons)

A: Also good with this

>3) Unify scoring levels
>3.1) Remove the star rating. I believe it's a decent rating as per
rationale - it also favors having 5 stars everywhere (no half measures),
but it sadly did not see much adoption.

A: Good with this too

>3.2) Adopt A-F rating and officially document it. It is used by ssllabs
and is well understood. Arguably, people are either A, B, or "bad up to F"
(which is similar to star rating, which would be 1 star, 3 stars or 5
stars). A- A+ etc not allowed as it makes the rating unclear.

A: Grade letters are ok for some things, but I honestly feel like severity
ratings should not be a grade letter - our standard high medium low etc.
should remain (couldn't tell if the severity ratings were a part of this
revamp)

>3.3) Discuss modern-intermediate-old (also should it be
Modern-legacy-deprecated?). In particular not using "modern" automatically
means you're not getting a 5 star or "A" rating - thus it actually make
sense, that people understood it as a scoring rating - it affects your
score directly.

A: I'm good with this

>3.4) Document bugzilla keywords directly in
https://wiki.mozilla.org/Security/Standard_Levels and discuss the current
nomenclature (can we alias sec-critical to sec-maximum and use the normal
levels?)

A: Yes please

>3.5) Revamp https://wiki.mozilla.org/Security_Severity_Ratings and clearly
deprecate all keywords that are no longer used (wsec, opsec for ex). Add
rationale on how keywords are added and why it's a good idea to keep the
list small.

A: Yes please

**Comment by amuntner** [comment]
I've been following along and didn't have anything new to add previously. I agree with your goal to have a a more meaning meaningful compliance score that is used consistently.

I took another look at 3.2,
"3.2 A-F rating (non-standard) rating used in https://mozilla.github.io/http-observatory-website/analyze.html?host=mozilla.com" 

The intent of the star ratings appears to have been to document standards compliance, recording whether MUST and/or SHOULD standards have been met. My main complaint about the star ratings is that they are too vague, the terms used (minimal, moderate, or most) to differentiate grades are subjective and vague.

What would the A-F ratings would look like? SSL Labs uses a quantitative scoring method based on specific protocol configurations. 
https://www.ssllabs.com/downloads/SSL_Server_Rating_Guide.pdf
For a single protocol like TLS/HTTPS this makes sense. 
I don't understand how we will would generate the scores for other subject areas in a repeatable way. 

Taking a step back I am not sure I understand what we're trying to rate here, compliance? deficiency/risk? The Internal Auditors guide has some examples that could help us formulate our intent: https://www.theiia.org/chapters/pubdocs/87/OPINIONS_PRACTICE_GUIDE_FINAL.PDF

Section 5, P. 13: Use of Grades in Expressing an Opinion
(Guidance on creating one)

Appendix B, P. 15: Examples: Micro and Macro 
Audit Opinion (Grading)
Grading examples

The first on P. 16 is a "macro" controls review rating. We might use a scale like this to describe how some asset meets our standards, could be website, service, database server, application environment, whatever the borders of the review are.

P. 17 "Company E:- 5 Tier Grading With Scale," it uses A-C and F scores, omitting D and E. 

Individual controls are specified in our own policies using RFC 2219 standards. There are different ways we measure these, as appropriate:

1. Pass/Fail in compliance with MUST clauses
2. A more nuanced way that does what the star ratings attempted to do: fall/pass/some way of describing SHOULD standards met.

**Comment by gdestuynder** [comment]
@marumari 

> Where does it get a bad score? It's "Intermediate" (with a green "I") on the Observatory, and it gets an A+ on SSL Labs.

My bad - I meant that it's seen as "not the best" (obviously modern is better) but didn't check the ratings *we* use did not actually represent it that way. 

@Phrozyn 

The standard levels are required yes - but weren't followed in particular by our team. I figured having this discussion is a sane approach to reconciliation and start following them again. For others teams, well to be honest they rarely need or use them so far. I think arguable it'd be ok to say its only required for us (but others can choose to follow it).

@amuntner 
Thanks for chiming in - I think your rationale is close to @Phrozyn and mine.
We in fact have definitions for max-hi-med-low that have been flushed out and revised over the years - and have been stable for a long while now (couple of years?) which to me means they're mature and they work. We introduced the "scores" as something non-security-minded people could more easily identify as "hey you're good/safe" vs "hey this is bad/unsafe" (hence how we started with a star rating).

I believe we should match up the ratings actually, and what you say makes sense for that too.
That'd mean A, B, C, F or A+, A, B, F for example (which I actually suspect some of us will feel its not enough definition maybe).
I spent some time looking at this for https obs in particular (@marumari probably spent more time though) here: https://docs.google.com/spreadsheets/d/16VYy9e8Gq5X5peek64ZEHNBpl3vjojxhwupHlz7nyxA/edit#gid=33423257
This compares scoring distribution to see how much sense it makes to use a more concise score method:

![meh](https://cloud.githubusercontent.com/assets/956866/17305344/d9eff1bc-57de-11e6-9135-dd17a8b33c7a.png)

Arguably having less scoring labels is not really changing the story behind data on http obs.

I suspect A+, B, C, F (MAX/HIGH/MED/LOW) is pretty decent here, though I expect some in the team still want a more granular method  such as A+, A, B, C, F or A+, A, B, C, D, F even thus these would have descriptions pretty much matching MAX (A+, A), HIGH (B), MEDIUM (C, D), LOW (F)

**Comment by amuntner** [comment]
Guillaume,

Yes, we're on the same track.

For the letter grades, what states or properties are we using a score to
understand and communicate? Good/safe are subjective and from a time before
we could have real standards, and compliance is an objective standard. Can
we infer anything about the policy compliance state from the letter grade
with certainty?
How do we apply the score to things where there is not a direct way to turn
a quantitatively derived number, like April does with the HTTP Observatory
ratings?
Which of the HTTP observatory letter grade matches up to the line of what
our standards define as MUST? (Not SHOULD.)

**Comment by gdestuynder** [comment]
@amuntner I would think that ideally, the observatory should be more operationally focused and display something closer to "modern-intermediate-old" (even thus id like better names there) and show "how far you are from reaching modern or intermediate or old".
This makes the job easy for ops to actually implement and its also easier for us to define what this "score" or *target state* means/is. (to your point: "we need definitions")
For this, you cannot derive from a quantitative number. You instead have a judgement call on wether or not the setting is required or not for the target (instead of a judgement call for how much weight a setting has/what "number it has")

The score rating makes it more of a gamification which is also a good thing, though the former seems more efficient to me as it clearly states the recommended targets.

As for actual definitions of the levels what we have is at https://wiki.mozilla.org/Security/Standard_Levels#Scoring_levels and https://wiki.mozilla.org/Security/Standard_Levels#Risk_levels_definition_and_nomenclature

For ex:
> *****
> Highest possible grade.
>
>    All intentions of objective met.
>    Attention expected but not required.

**Comment by Phrozyn** [comment]
Maybe we could take those scores and show how they are equivalent to
modern/intermediate/deprecated so people can more easily grok their value
An A = current acceptable configuration, B= ok for extreme cases?
F= DEPRECATED, update to A or B asap?

Just tossing ideas around.

**Comment by floatingatoll** [comment]
For the TLS guidelines, there's actually four levels: modern, intermediate,
deprecated, plaintext. We've never talked about the fourth one
("plaintext") in any of our documents, because we don't *guide* people to
configure plaintext (SSLv2, or cipher=none, or trivially MitM-able, etc.)
But it's absolutely a possibility when scanning sites, and plaintext and
deprecated are not equivalently at-risk for TLS. So, since plaintext can
only receive an F, I would assume that deprecated - while not *ideal* -
qualifies as, at the very least an attempt, and is indeed better than
plaintext: so "deprecated" should get a D, not an F, when translating from
TLS scoring levels to letter grades.

**Comment by marumari** [comment]
Note that I'm not at all opposed to having fewer states in general when we use a grading system.  I personally think that fewer states is generally better.

I just think that the Mozilla Observatory should continue to use its current scale for two reasons:

- Other scanners on the internet use the same scale, so people are familiar with it
- It gives people good feeling when they make an actual improvement (even if minor) and their grade changes.  If implementing X-Frame-Options moved them from a B to a B, then they're not going nearly as excited about continuing to make things better.  Gamification is good for adoption.

**Comment by amuntner** [comment]
I agree with April, the scale for Observatory is an aggregate score, that's not what we're trying to represent here. 

I like the approach in the old scoring mechanism wiki doc[1] which describes what the scoring mechanism is and what it means, and drafted a new version based on what we have been discussing:

**Scoring Levels**
Four levels are used to communicate compliance with Mozilla standards and RFC 2119 "must" and "should" statements. 
Since Mozilla's policies and standards represent its desired security posture, these levels are used to inform about controls effectiveness and risk based on policy and standard compliance.

A **** - Exceeds compliance with all policies and standards - Meets the standard or policy objective and requirements. All "must" statements are effectively fulfilled. Additionally, "should" clauses that significantly improve security have been followed.

B *** - Compliant with all policies and standards - Meets the standard or policy objective and requirements. All "must" statements are effectively fulfilled. 

C ** - Meets some, not all policies and standards - Some, but not all "must" statements have been fulfilled, or some "must"clauses have been incompletely or ineffectively followed. 

F * - Meets no or nearly no and violates all or nearly all policies and standards - Does not conform with relevant policy or standard at all. 

1. https://wiki.mozilla.org/Security/Standard_Levels#Scoring_levels

**Comment by gdestuynder** [comment]
The issue with http obs is that it is an aggregate score of weighted features vs and aggregate score of recommended target state ("a standard")

Adam's rating in https://github.com/mozilla/wikimo_content/issues/50#issuecomment-236734521actually use target states (A and B reach recommended target state, C and F do not).

**Comment by gdestuynder** [comment]
Current proposal is: A+, A, B, C, F for scoring
Cutting-edge, recommended, legacy for states

http obs keeps doing scores and a separate service does state compliance

I think at this point I can draft a PR

**Comment by gdestuynder** [comment]
A simplified version of the current levels have been drafted at https://wiki.mozilla.org/User:Gdestuynder/test

**Comment by amuntner** [comment]
Thanks! 

This is an opportunity for us to do take all the standards we've been defining and measure things according to them. We have "RFC2119 handling recommendation levels" for defining standards: must, should, or optional. We still need a score to represent compliance states.  @tristanweir thoughts? For risk, we have low, medium, high, maximum. We have nothing existing for scoring policy compliance because it's new for Mozilla. 

Assuming that our policies and standards represent our target level of risk acceptance, only Grade A represents fulfilling all "must" requirements,  with A+ being all "must" and some "should" and "optional" statements. I think this is the right way too, but anything less than A is not compliant. Using our scale, everything should reach A grade and if not there should be risk records and bugs to define and track the work. 

I adapted your new scoring system to represent states of policy compliance  It's a scale where "policy compliance" is the baseline and scores represent a point either above or below that. Above it there is only one level that makes sense, and below it I think there are two states: F for failure, another point that is better than nothing but less than fully compliant.. It doesn't matter for the purposes of scoring security policy compliance that some issues might be much worse than others, we have other ways to do that such as low/medium/high/maximum ratings and the corresponding SLA for security bugs. 

**A+**
_Exceeds policy requirements+
- All "must" statements are effectively fulfilled
- Compliant with Mozilla security policy, plus "should" and "optional" directives that improve security.

**A**
_Policy-compliant_
- All "must" statements are effectively fulfilled
- Compliant with Mozilla security policies. 

**D**
_Score represents a moderate level of risk_
- Potential service blocker. Meets some, not all policies and standards
- Minimal to moderate intentions of control objectives have been met
- Triage is required. Open a risk record or Bugzilla issue as appropriate for remediation of the compliance issue(s). 

**F**
_Likely service blocker_
- Zero to minimal intentions of control objectives have been met
- Meets no or nearly no and violates all or nearly all policies and standards - Does not conform with relevant policy or standard at all. 
- Immediate action is required

**Comment by amuntner** [comment]
For 
_3.5) Revamp https://wiki.mozilla.org/Security_Severity_Ratings and clearly deprecate all keywords that are no longer used (wsec, opsec for ex). Add rationale on how keywords are added and why it's a good idea to keep the list small._

We use the wsec keywords for tracking issue categories for metrics and query purposes

**Comment by gdestuynder** [comment]
@amuntner the scoring system is differentiating the recommended configuration states (compliance) from aggregated scoring.
If scores are used for compliance then states and scores are redundant, and back to square one.

**Comment by jeffbryner** [comment]
@gdestuynder looks like we are collapsing to removing the D grade. Might be nice to include rationale for why no D in the wiki since it's a common/expected tier?

**Comment by gdestuynder** [comment]
Definitely a good point, I've added some kind of rationale for D,E being removed (even thus E is commonly removed its not always obvious to non-north-americans IMO) and for A+ being added

https://wiki.mozilla.org/index.php?title=User%3AGdestuynder%2Ftest&diff=1143334&oldid=1143213

**Comment by gdestuynder** [comment]
(see also https://github.com/mozilla/wikimo_content/issues/34 on how configuration states work better for some things IMO)

**Comment by gdestuynder** [comment]
After more deliberation with the interested parties and so on I have decided to give this document another attempt (which I feel like is the best one so far):

https://wiki.mozilla.org/User:Gdestuynder/test (Main doc for standard levels)
https://wiki.mozilla.org/User:Gdestuynder/test/Scoring_and_other_levels (sub doc)

What this achieve is:
- Much clearer focus on risk where levels are mandatory without exception (they're also more complete now)
- Enough flexibility ("should") on scoring and so on, while still giving the proper guidance and expectation

**Comment by gdestuynder** [comment]
@jeffbryner @amuntner @alm for review of https://wiki.mozilla.org/User:Gdestuynder/test exception time in particular

**Comment by gdestuynder** [comment]
moving reviews to the PR at https://github.com/mozilla/wikimo_content/pull/63

**Comment by gdestuynder** [comment]
this is live, thx everyone
